- name: Install OpenVPN, EasyRSA, OpenLDAP, phpLDAPAdmin and DNSMasq
  become: true
  apt:
   name: "{{ item }}" 
   update_cache: yes
  with_items:
   - openvpn
   - openvpn-auth-ldap
   - easy-rsa
   - slapd
   - phpldapadmin
   - dnsmasq

- include: openldap.yml
- include: easyrsa.yml
- include: openvpn.yml
- include: phpldapadmin.yml
- include: dnsmasq.yml
